### ISSUE TITLE
ModuleNotFoundError: No module named 'google'

### ISSUE THREAD

**Issue by pkuphy** [dfuse-io/example-graphql-python#1]
```
Traceback (most recent call last):
  File "example.py", line 8, in <module>
    from graphql import graphql_pb2_grpc
  File "/Users/me/Developer/dapp/dfuse/example-graphql-python/graphql/graphql_pb2_grpc.py", line 4, in <module>
    from graphql import graphql_pb2 as graphql_dot_graphql__pb2
  File "/Users/me/Developer/dapp/dfuse/example-graphql-python/graphql/graphql_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google'
```

**Comment by maoueh** [comment]
@sduchesneau I think you had a similar problem, was it a Python 2 vs Python 3 problems?

**Comment by pkuphy** [comment]
I'm using python 3.7.4 and grpc 1.22.0

**Comment by maoueh** [comment]
It seems this `No module named 'google'` module was coming from `grpcio-tools`. I have converted the example now to use `virtualenv`. There is a `requirements.txt` also now in the repository directly with the working dependencies.

The readme has been updated also for the new way to run the example.

Sorry for the wait time and having left you in limbo.

**Comment by pkuphy** [comment]
Thanks for the fix!
