### ISSUE TITLE
Adapting to WAX Network

### ISSUE THREAD

**Issue by steeljardas** [dfuse-io/example-graphql-python#2]
So I'm trying to adapt this to WAX Network using the EOSNATION Free API, this is what I have:

`def stub():
    credentials = grpc.access_token_call_credentials(token_for_api_key(apiKey))
    channel = grpc.secure_channel('wax.dfuse.eosnation.io:9000',
                                  credentials=grpc.composite_channel_credentials(grpc.ssl_channel_credentials(),
                                                                                 credentials))
    return graphql_pb2_grpc.GraphQLStub(channel)`
    
However when it runs:
dfuse_graphql = stub()
stream = dfuse_graphql.Execute(Request(query=query))
for rawResult in stream:

I get an error:
`status = StatusCode.UNIMPLEMENTED
	details = "unknown service dfuse.eosio.v1.GraphQL"
	debug_error_string = "{"created":"@1626216788.250000000","description":"Error received from peer ipv4:216.66.39.210:9000","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"unknown service dfuse.eosio.v1.GraphQL","grpc_status":12}"`

Is this related to the protobuf since it's WAX and not EOS? and if it is how can I fix/get the info/files needed for WAX to work?

**Comment by maoueh** [comment]
I've re-wrote the example to use the latest protobuf definition as well as improving some common patterns like passing a variables array as a well-known protobuf `struct` type.
